### ISSUE TITLE
Error: Extensions must be a non empty array

### ISSUE THREAD

**Issue by avoelkl** [gordonknoppe/magento-cachebuster#5]
Hi,

I got this error during updating Guidance_Cachebuster to the lastest version:
```
Extensions must be a non empty array

Trace:
#0 Guidance_Cachebuster/src/app/code/community/Guidance/Cachebuster/Model/Parser.php(35): Guidance_Cachebuster_Model_Parser->setFileExtensions(Array)
#1 app/code/core/Mage/Core/Model/Config.php(1348): Guidance_Cachebuster_Model_Parser->__construct(Array)
#2 app/Mage.php(463): Mage_Core_Model_Config->getModelInstance('guidance_cacheb...', Array)
#3 Guidance_Cachebuster/src/app/code/community/Guidance/Cachebuster/Helper/Data.php(98): Mage::getModel('guidance_cacheb...', Array)
#4 Guidance_Cachebuster/src/app/code/community/Guidance/Cachebuster/Model/Observer.php(40): Guidance_Cachebuster_Helper_Data->getParser()
#5 app/code/local/Mage/Core/Model/App.php(1334): Guidance_Cachebuster_Model_Observer->controller_action_postdispatch(Object(Varien_Event_Observer))
#6 app/code/local/Mage/Core/Model/App.php(1313): Mage_Core_Model_App->_callObserverMethod(Object(Guidance_Cachebuster_Model_Observer), 'controller_acti...', Object(Varien_Event_Observer))
#7 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#8 app/code/core/Mage/Core/Controller/Varien/Action.php(551): Mage::dispatchEvent('controller_acti...', Array)
#9 app/code/core/Mage/Core/Controller/Front/Action.php(80): Mage_Core_Controller_Varien_Action->postDispatch()
#10 app/code/core/Mage/Core/Controller/Varien/Action.php(422): Mage_Core_Controller_Front_Action->postDispatch()
#11 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 app/code/local/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#15 index.php(87): Mage::run('...', 'store')
#16 {main}
```

I saw there was a change in Guidance_Cachebuster_Helper_Data lately which initializes the protected $_fileExtensions = array(); 
Therefor the check is_null($this->_fileExtensions) is always false and fileExtensions do not get initialized.
https://github.com/gordonknoppe/magento-cachebuster/commit/65f661c197881a6fc0af50d20981eb195b5bd122#diff-55a9881a212332774228ad08b74ccffcL33

So you can either remove the initialization again or change the check, not sure what you prefer :-)

**Comment by gordonknoppe** [comment]
Fixed
